form	lemma	xpostag	gold	NP-BIO
Hétfőn	hétfő	[/N][Supe]	1-NP	1-NP
folytatódik	folytatódik	[/V][Prs.NDef.3Sg]	O	O
az	az	[/Det|Art.Def]	B-NP	B-NP
Investicná	Investicná	[/N][Nom]	I-NP	I-NP
a	a	[/Det|Pro|(Post)]	I-NP	I-NP
Rozvojová	Rozvojová	[/N][Nom]	I-NP	I-NP
Banka	Banka	[/N][Nom]	I-NP	I-NP
(	(	[Punct]	I-NP	I-NP
IRB	IRB	[/N][Nom]	I-NP	I-NP
)	)	[Punct]	I-NP	I-NP
auditja	audit	[/N][Poss.3Sg][Nom]	E-NP	E-NP
,	,	[Punct]	O	O
az	az	[/Det|Art.Def]	B-NP	B-NP
OTP	OTP	[/N][Nom]	I-NP	I-NP
Bank	Bank	[/N][Nom]	I-NP	I-NP
szakemberei	szakember	[/N][Pl.Poss.3Sg][Nom]	I-NP	I-NP
és	és	[/Cnj]	I-NP	I-NP
tanácsadói	tanácsadó	[/N][Pl.Poss.3Sg][Nom]	E-NP	E-NP
ismét	ismét	[/Adv]	O	O
felkeresik	felkeres	[/V][Prs.Def.3Pl]	O	O
a	a	[/Det|Art.Def]	B-NP	B-NP
bank	bank	[/N][Nom]	I-NP	I-NP
adatszobáját	adatszoba	[/N][Poss.3Sg][Acc]	E-NP	E-NP
-	-	[Punct]	O	O
közölte	közöl	[/V][Pst.Def.3Sg]	O	O
Wolf	Wolf	[/N][Nom]	B-NP	B-NP
László	László	[/N][Nom]	I-NP	I-NP
,	,	[Punct]	I-NP	I-NP
az	az	[/Det|Art.Def]	I-NP	I-NP
OTP	OTP	[/N][Nom]	I-NP	I-NP
Bank	Bank	[/N][Nom]	I-NP	I-NP
vezérigazgató-helyettese	vezérigazgató-helyettes	[/N][Poss.3Sg][Nom]	E-NP	E-NP
az	az	[/Det|Art.Def]	B-NP	B-NP
MTI	MTI	[/N][Nom]	I-NP	I-NP
érdeklődésére	érdeklődés	[/N][Poss.3Sg][Subl]	E-NP	E-NP
.	.	[Punct]	O	O

Befejeződött	befejeződik	[/V][Pst.NDef.3Sg]	O	O
az	az	[/Det|Art.Def]	B-NP	B-NP
IRB	IRB	[/N][Nom]	I-NP	I-NP
auditálása	auditálás	[/N][Poss.3Sg][Nom]	E-NP	E-NP
-	-	[Punct]	O	O
tájékoztatták	tájékoz	[/V][_Caus/V][Pst.Def.3Pl]	O	O
a	a	[/Det|Art.Def]	B-NP	B-NP
pénzintézetnél	pénzintézet	[/N][Ade]	E-NP	E-NP
kedden	kedd	[/N][Supe]	1-NP	1-NP
az	az	[/Det|Art.Def]	B-NP	B-NP
MTI-t	MTI	[/N][Acc]	E-NP	E-NP
.	.	[Punct]	O	O

Az	az	[/Det|Art.Def]	B-NP	B-NP
Ernst	Ernst	[/N][Nom]	I-NP	I-NP
and	and	[/N][Nom]	I-NP	I-NP
Young	Young	[/N][Nom]	I-NP	I-NP
Könyvvizsgáló	Könyvvizsgáló	[/N][Nom]	I-NP	I-NP
Kft-t	kft	[/N|Acron][Acc]	E-NP	E-NP
javasolja	javasol	[/V][Prs.Def.3Sg]	O	O
a	a	[/Det|Art.Def]	B-NP	B-NP
Magyar	Magyar	[/N][Nom]	I-NP	I-NP
Nemzeti	Nemzeti	[/N][Nom]	I-NP	I-NP
Bank	Bank	[/N][Nom]	I-NP	I-NP
könyvvizsgálójának	könyvvizsgáló	[/N][Poss.3Sg][Dat]	E-NP	E-NP
az	az	[/Det|Art.Def]	B-NP	B-NP
Állami	Állami	[/N][Nom]	I-NP	I-NP
Számvevőszék	Számvevőszék	[/N][Nom]	I-NP	I-NP
(	(	[Punct]	I-NP	I-NP
ÁSZ	ÁSZ	[/N][Nom]	I-NP	I-NP
)	)	[Punct]	I-NP	I-NP
elnöke	elnök	[/N][Poss.3Sg][Nom]	E-NP	E-NP
-	-	[Punct]	O	O
tájékoztatta	tájékoz	[/V][_Caus/V][Pst.Def.3Sg]	O	O
az	az	[/Det|Art.Def]	B-NP	B-NP
ÁSZ	ÁSZ	[/N][Nom]	E-NP	E-NP
az	az	[/Det|Art.Def]	B-NP	B-NP
MTI-t	MTI	[/N][Acc]	E-NP	E-NP
hétfőn	hétfő	[/N][Supe]	1-NP	1-NP
közleményben	közlemény	[/N][Ine]	1-NP	1-NP
.	.	[Punct]	O	O

Immár	immár	[/Adv]	O	O
negyedik	négy	[/Num][_Ord/Adj][Nom]	B-NP	B-NP
éve	év	[/N][Poss.3Sg][Nom]	E-NP	E-NP
a	a	[/Det|Art.Def]	B-NP	B-NP
brit	brit	[/Adj][Nom]	I-NP	I-NP
Manchester	Manchester	[/N][Nom]	I-NP	I-NP
United	United	[/N][Nom]	I-NP	I-NP
labdarúgó	labdarúgó	[/Adj][Nom]	I-NP	I-NP
klub	klub	[/N][Nom]	E-NP	E-NP
a	a	[/Det|Art.Def]	B-NP	B-NP
világ	világ	[/N][Nom]	I-NP	I-NP
leggazdagabb	gazdag	[/Supl][/Adj][_Comp/Adj][Nom]	I-NP	I-NP
csapata	csapat	[/N][Poss.3Sg][Nom]	E-NP	E-NP
bevétel	bevétel	[/N][Nom]	O	O
szerint	szerint	[/Post]	O	O
-	-	[Punct]	O	O
közölte	közöl	[/V][Pst.Def.3Sg]	O	O
pénteken	péntek	[/N][Supe]	1-NP	1-NP
a	a	[/Det|Art.Def]	B-NP	B-NP
Deloitte	Deloitte	[/N][Nom]	I-NP	I-NP
and	and	[/N][Nom]	I-NP	I-NP
Touche	Touche	[/N]	E-NP	E-NP
.	.	[Punct]	O	O

