form	lemma	xpostag	gold	NER-BIO
Hétfőn	hétfő	[/N][Supe]	O	O
folytatódik	folytatódik	[/V][Prs.NDef.3Sg]	O	O
az	az	[/Det|Art.Def]	O	O
Investicná	Investicná	[/N][Nom]	B-ORG	B-ORG
a	a	[/Det|Pro|(Post)]	I-ORG	I-ORG
Rozvojová	Rozvojová	[/N][Nom]	I-ORG	I-ORG
Banka	Banka	[/N][Nom]	E-ORG	E-ORG
(	(	[Punct]	O	O
IRB	IRB	[/N][Nom]	1-ORG	1-ORG
)	)	[Punct]	O	O
auditja	audit	[/N][Poss.3Sg][Nom]	O	O
,	,	[Punct]	O	O
az	az	[/Det|Art.Def]	O	O
OTP	OTP	[/N][Nom]	B-ORG	B-ORG
Bank	Bank	[/N][Nom]	E-ORG	E-ORG
szakemberei	szakember	[/N][Pl.Poss.3Sg][Nom]	O	O
és	és	[/Cnj]	O	O
tanácsadói	tanácsadó	[/N][Pl.Poss.3Sg][Nom]	O	O
ismét	ismét	[/Adv]	O	O
felkeresik	felkeres	[/V][Prs.Def.3Pl]	O	O
a	a	[/Det|Art.Def]	O	O
bank	bank	[/N][Nom]	O	O
adatszobáját	adatszoba	[/N][Poss.3Sg][Acc]	O	O
-	-	[Punct]	O	O
közölte	közöl	[/V][Pst.Def.3Sg]	O	O
Wolf	Wolf	[/N][Nom]	B-PER	B-PER
László	László	[/N][Nom]	E-PER	E-PER
,	,	[Punct]	O	O
az	az	[/Det|Art.Def]	O	O
OTP	OTP	[/N][Nom]	B-ORG	B-ORG
Bank	Bank	[/N][Nom]	E-ORG	E-ORG
vezérigazgató-helyettese	vezérigazgató-helyettes	[/N][Poss.3Sg][Nom]	O	O
az	az	[/Det|Art.Def]	O	O
MTI	MTI	[/N][Nom]	1-ORG	1-ORG
érdeklődésére	érdeklődés	[/N][Poss.3Sg][Subl]	O	O
.	.	[Punct]	O	O

Befejeződött	befejeződik	[/V][Pst.NDef.3Sg]	O	O
az	az	[/Det|Art.Def]	O	O
IRB	IRB	[/N][Nom]	1-ORG	1-ORG
auditálása	auditálás	[/N][Poss.3Sg][Nom]	O	O
-	-	[Punct]	O	O
tájékoztatták	tájékoz	[/V][_Caus/V][Pst.Def.3Pl]	O	O
a	a	[/Det|Art.Def]	O	O
pénzintézetnél	pénzintézet	[/N][Ade]	O	O
kedden	kedd	[/N][Supe]	O	O
az	az	[/Det|Art.Def]	O	O
MTI-t	MTI	[/N][Acc]	1-ORG	1-ORG
.	.	[Punct]	O	O

Az	az	[/Det|Art.Def]	O	O
Ernst	Ernst	[/N][Nom]	B-ORG	B-ORG
and	and	[/N][Nom]	I-ORG	I-ORG
Young	Young	[/N][Nom]	I-ORG	I-ORG
Könyvvizsgáló	Könyvvizsgáló	[/N][Nom]	I-ORG	I-ORG
Kft.-t	Kft.	[Punct]	E-ORG	E-ORG
javasolja	javasol	[/V][Prs.Def.3Sg]	O	O
a	a	[/Det|Art.Def]	O	O
Magyar	Magyar	[/N][Nom]	B-ORG	B-ORG
Nemzeti	Nemzeti	[/N][Nom]	I-ORG	I-ORG
Bank	Bank	[/N][Nom]	E-ORG	E-ORG
könyvvizsgálójának	könyvvizsgáló	[/N][Poss.3Sg][Dat]	O	O
az	az	[/Det|Art.Def]	O	O
Állami	Állami	[/N][Nom]	B-ORG	B-ORG
Számvevőszék	Számvevőszék	[/N][Nom]	E-ORG	E-ORG
(	(	[Punct]	O	O
ÁSZ	ÁSZ	[/N][Nom]	1-ORG	1-ORG
)	)	[Punct]	O	O
elnöke	elnök	[/N][Poss.3Sg][Nom]	O	O
-	-	[Punct]	O	O
tájékoztatta	tájékoz	[/V][_Caus/V][Pst.Def.3Sg]	O	O
az	az	[/Det|Art.Def]	O	O
ÁSZ	ÁSZ	[/N][Nom]	1-ORG	1-ORG
az	az	[/Det|Art.Def]	O	O
MTI-t	MTI	[/N][Acc]	1-ORG	1-ORG
hétfőn	hétfő	[/N][Supe]	O	O
közleményben	közlemény	[/N][Ine]	O	O
.	.	[Punct]	O	O

Immár	immár	[/Adv]	O	O
negyedik	négy	[/Num][_Ord/Adj][Nom]	O	O
éve	év	[/N][Poss.3Sg][Nom]	O	O
a	a	[/Det|Art.Def]	O	O
brit	brit	[/Adj][Nom]	O	O
Manchester	Manchester	[/N][Nom]	B-ORG	B-ORG
United	United	[/N][Nom]	E-ORG	E-ORG
labdarúgó	labdarúgó	[/Adj][Nom]	O	O
klub	klub	[/N][Nom]	O	O
a	a	[/Det|Art.Def]	O	O
világ	világ	[/N][Nom]	O	O
leggazdagabb	gazdag	[/Supl][/Adj][_Comp/Adj][Nom]	O	O
csapata	csapat	[/N][Poss.3Sg][Nom]	O	O
bevétel	bevétel	[/N][Nom]	O	O
szerint	szerint	[/Post]	O	O
-	-	[Punct]	O	O
közölte	közöl	[/V][Pst.Def.3Sg]	O	O
pénteken	péntek	[/N][Supe]	O	O
a	a	[/Det|Art.Def]	O	O
Deloitte	Deloitte	[/N][Nom]	B-ORG	B-ORG
and	and	[/N][Nom]	I-ORG	I-ORG
Touche	Touche	[/N]	E-ORG	E-ORG
.	.	[Punct]	O	O

